# Generated by Django 4.1.7 on 2023-03-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_ticket_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.CharField(choices=[('otro', 'Otro'), ('contabilidad', 'Contabilidad'), ('rrhh', 'RRHH'), ('legal', 'Legal'), ('informatica', 'Informatica')], default='otro', max_length=50),
        ),
    ]
