# Generated by Django 4.1.7 on 2023-03-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_remove_estado_usuario_remove_prioridad_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'abierto'), ('En progreso', 'en_progreso'), ('Resuelto', 'resuelto'), ('Cerrado', 'cerrado')], default='Abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='estado',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estado',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='prioridad',
            field=models.CharField(choices=[('Normal', 'normal'), ('Baja', 'baja'), ('Alta', 'alta')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.CharField(choices=[('otro', 'Otro'), ('contabilidad', 'Contabilidad'), ('rrhh', 'RRHH'), ('legal', 'Legal'), ('informatica', 'Informatica')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
